// Mock product data for development/demo when Supabase is not yet connected
export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: 'Precision Digital Microscope Z-1',
    category: 'Optics & Imaging',
    description: 'High-resolution 4K sensor with integrated auto-calibration firmware and multi-lens array. Designed for advanced pathology and industrial micro-inspection.',
    price: 12499,
    original_price: 15999,
    image_url: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=600&q=80',
      'https://images.unsplash.com/photo-1585760026994-e5f12ccc879d?w=600&q=80',
    ],
    rating: 4.9,
    reviews: 128,
    in_stock: true,
    is_featured: true,
    is_active: true,
    specs: {
      'Magnification Range': '50x - 2000x Digital',
      'Sensor': 'Sony EXMOR 48MP CMOS',
      'Interface': 'HDMI 2.1 / USB-C 3.2',
      'Resolution': '0.02μm',
      'Color Depth': '12-Bit',
    },
    certifications: ['ISO-9001:2015', 'CE MED 93/42'],
    badge: 'BESTSELLER',
  },
  {
    id: '2',
    name: 'Hematology Analyser HA-36',
    category: 'Diagnostics',
    description: '36-parameter throughput with high-speed automated processing and wireless data sync. Perfect for clinical labs.',
    price: 5800,
    original_price: 7200,
    image_url: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=600&q=80'],
    rating: 4.7,
    reviews: 85,
    in_stock: true,
    is_featured: true,
    is_active: true,
    specs: {
      'Parameters': '36-channel',
      'Processing Speed': '120 samples/hr',
      'Connectivity': 'Wi-Fi + LAN',
    },
    certifications: ['ISO-13485', 'CE IVD'],
    badge: 'POPULAR',
  },
  {
    id: '3',
    name: 'Advanced Centrifuge X-400',
    category: 'Lab Equipment',
    description: 'High-speed refrigerated centrifuge with programmable rotor management and safety interlocks. For research and clinical use.',
    price: 4250,
    original_price: 5100,
    image_url: 'https://images.unsplash.com/photo-1614935151651-0bea6508db6b?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1614935151651-0bea6508db6b?w=600&q=80'],
    rating: 4.8,
    reviews: 62,
    in_stock: true,
    is_featured: true,
    is_active: true,
    specs: {
      'Max RPM': '25,000',
      'Capacity': '24 × 1.5ml tubes',
      'Temperature Range': '-20°C to +40°C',
    },
    certifications: ['ISO-9001:2015'],
  },
  {
    id: '4',
    name: 'PCR Thermocycler Pro',
    category: 'Molecular Biology',
    description: 'Next-generation real-time PCR system with 96-well format, gradient capability, and cloud connectivity for remote monitoring.',
    price: 8900,
    original_price: 11500,
    image_url: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=600&q=80'],
    rating: 4.9,
    reviews: 44,
    in_stock: true,
    is_featured: true,
    is_active: true,
    specs: {
      'Well Format': '96-well',
      'Temperature Accuracy': '±0.1°C',
      'Ramp Rate': '5°C/sec',
    },
    certifications: ['CE IVD', 'UL Listed'],
  },
  {
    id: '5',
    name: 'Mass Spectrometer MS-V2',
    category: 'Analytical Instruments',
    description: 'Compact benchtop mass spectrometer with ESI and APCI ionization sources. Ideal for pharmaceutical and clinical research.',
    price: 12800,
    original_price: 16000,
    image_url: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&q=80'],
    rating: 4.6,
    reviews: 29,
    in_stock: false,
    is_featured: false,
    is_active: true,
    specs: {
      'Mass Range': '50 - 3000 m/z',
      'Resolution': '10,000 FWHM',
      'Ionization': 'ESI / APCI',
    },
    certifications: ['ISO-17025', 'CE Marked'],
  },
  {
    id: '6',
    name: 'Lab Incubator Pro 5',
    category: 'Lab Equipment',
    description: 'CO2 incubator with HEPA filtration, 180° thermal disinfection, and dual-beam IR CO2 sensing.',
    price: 2100,
    original_price: 2800,
    image_url: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1576086213369-97a306d36557?w=600&q=80'],
    rating: 4.5,
    reviews: 37,
    in_stock: true,
    is_featured: false,
    is_active: true,
    specs: {
      'Capacity': '170 Liters',
      'CO2 Range': '0 - 20%',
      'Temperature': '5°C above ambient to 50°C',
    },
    certifications: ['ISO-13485', 'CE Marked'],
  },
  {
    id: '7',
    name: 'Calibration Slide Set (NIST)',
    category: 'Consumables',
    description: 'NIST-traceable precision calibration slides for microscopy. Set of 12 calibrated reference slides.',
    price: 249,
    original_price: null,
    image_url: 'https://images.unsplash.com/photo-1559131397-f94da358f7ca?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1559131397-f94da358f7ca?w=600&q=80'],
    rating: 4.8,
    reviews: 91,
    in_stock: true,
    is_featured: false,
    is_active: true,
    specs: {
      'Quantity': '12 slides',
      'Traceable': 'NIST',
      'Material': 'Borosilicate glass',
    },
    certifications: ['NIST Traceable'],
  },
  {
    id: '8',
    name: 'Pipette Set Premium (A-Series)',
    category: 'Consumables',
    description: 'Ergonomic air-displacement pipette set with autoclavable lower parts. Volume range: 0.5μL to 1000μL. Set of 5.',
    price: 389,
    original_price: 499,
    image_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80'],
    rating: 4.7,
    reviews: 156,
    in_stock: true,
    is_featured: false,
    is_active: true,
    specs: {
      'Volume Range': '0.5μL - 1000μL',
      'Accuracy': '±0.6%',
      'Autoclavable': 'Yes (Lower part)',
    },
    certifications: ['ISO-8655'],
  },
]

export const CATEGORIES = [
  { id: 'all', label: 'All Products' },
  { id: 'Optics & Imaging', label: 'Optics & Imaging' },
  { id: 'Diagnostics', label: 'Diagnostics' },
  { id: 'Lab Equipment', label: 'Lab Equipment' },
  { id: 'Molecular Biology', label: 'Molecular Biology' },
  { id: 'Analytical Instruments', label: 'Analytical Instruments' },
  { id: 'Consumables', label: 'Consumables' },
]

export const CERTIFICATIONS = [
  { icon: '🏅', label: 'ISO 9001:2015', desc: 'Quality Management System' },
  { icon: '🇪🇺', label: 'CE Certified', desc: 'European Conformity' },
  { icon: '🔬', label: 'ISO 13485', desc: 'Medical Device Quality' },
  { icon: '📋', label: 'NABL Approved', desc: 'National Accreditation Board' },
]
